---
- name: "Create {{ foreman_installer_katello_certs_dir }}"
  file:
    path: "{{ foreman_installer_katello_certs_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Register cert files stat
  stat:
    path: "{{ item }}"
  with_items:
    - "{{ foreman_installer_katello_certs_dir }}/katello-ca-cert.pem"
    - "{{ foreman_installer_katello_certs_dir }}/katello-server-cert.cer"
    - "{{ foreman_installer_katello_certs_dir }}/katello-server-cert.key"
    - "{{ foreman_installer_katello_certs_dir }}/katello-server-cert.csr"
  register: certs_stat

- name: Write custom CA certificate file
  copy:
    content: "{{ foreman_installer_katello_ca }}"
    dest: "{{ foreman_installer_katello_certs_dir }}/katello-ca-cert.pem"
    owner: root
    group: root
    mode: 0600
  notify:
    - 'set foreman_installer_update_certs to True'
    - execute foreman-installer

- name: Write custom certificate file
  copy:
    content: "{{ foreman_installer_katello_cert }}"
    dest: "{{ foreman_installer_katello_certs_dir }}/katello-server-cert.cer"
    owner: root
    group: root
    mode: 0600
  notify:
    - 'set foreman_installer_update_certs to True'
    - execute foreman-installer

- name: Write custom key certificate file
  copy:
    content: "{{ foreman_installer_katello_key }}"
    dest: "{{ foreman_installer_katello_certs_dir }}/katello-server-cert.key"
    owner: root
    group: root
    mode: 0600
  notify:
    - 'set foreman_installer_update_certs to True'
    - execute foreman-installer

- name: Write custom CSR certificate file
  copy:
    content: "{{ foreman_installer_katello_csr }}"
    dest: "{{ foreman_installer_katello_certs_dir }}/katello-server-cert.csr"
    owner: root
    group: root
    mode: 0600
  notify:
    - 'set foreman_installer_update_certs to True'
    - execute foreman-installer

- name: Include katello certificate options in foreman_installer_scenarios_answers
  set_fact:
    foreman_installer_scenarios_answers: "{{ foreman_installer_scenarios_answers | combine( { 'certs': {'server_cert': foreman_installer_katello_certs_dir + '/katello-server-cert.cer','server_cert_req': foreman_installer_katello_certs_dir + '/katello-server-cert.csr','server_key': foreman_installer_katello_certs_dir + '/katello-server-cert.key','server_ca_cert': foreman_installer_katello_certs_dir + '/katello-ca-cert.pem' } }, recursive=True ) }}"
