---
- include: packages.yml

- include: module_pr.yml

- include: facts.yml

- include: installer.yml

- include: upgrade.yml
  when: foreman_installer_upgrade == True

- include: ha-extras.yml
  tags:
    - ha_extras
