---
- include: packages.yml

- include: locales.yml
  when: ansible_os_family == 'Debian'

- include: module_pr.yml
  when: foreman_installer_module_prs is defined

- include: facts.yml

- include: installer.yml

- include: upgrade.yml
  when: foreman_installer_upgrade == True

- include: ha-extras.yml
  tags:
    - ha_extras
