---
- name: "Add GPG keys"
  rpm_key:
    key: "{{ item }}"
    state: present
  with_items: "{{ el_gpg }}"
  when:
  - ansible_distribution in ["CentOS", "Red Hat Enterprise Linux"] and ansible_distribution_major_version == "7"
- name: "Add EL repositories"
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: "{{ item.gpgcheck | default(omit) }}"
  with_items: "{{ el_repos }}"
  when:
  - ansible_distribution in ["CentOS", "Red Hat Enterprise Linux"] and ansible_distribution_major_version == "7"
- name: "Add additional RHEL repositories"
  rhsm_repository:
    name:
      - rhel-7-server-rpms
      - rhel-7-server-extras-rpms
      - rhel-7-server-optional-rpms
  when:
  - ansible_distribution in ["Red Hat Enterprise Linux"] and ansible_distribution_major_version == "7"

- name: "Install dependencies"
  package: 
    name: "{{ item }}"
    state: "{{ foreman_installer_pkg_state }}"
  with_items: "{{ foreman_installer_dependencies | default( [] ) }}"
  
- name: "Install {{ foreman_installer_pkg }}"
  package:
    name: "{{ foreman_installer_pkg }}"
    state: "{{ foreman_installer_pkg_state }}"
  notify:
    - reload ansible_local
    - 'set dont_save_answers to False'
    - Workaround 18818

- name: Apply installer fixes
  patch:
    src: "{{ item.src }}"
    basedir: "{{ item.basedir }}"
    strip: "{{ item.strip | default(1) }}"
  with_items: "{{ foreman_installer_patches }}"
  when: foreman_installer_patches is defined
